import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { type RouterOutputs, api } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  console.log(user?.id);

  if (!user) {
    return null;
  }

  return (
    <div className="flex flex-1 items-center justify-start gap-4">
      <Image
        src={user.imageUrl}
        alt="Profile image"
        className="m-2 flex aspect-square h-14 rounded-lg"
        width={56}
        height={56}
      />
      <input
        placeholder="Express yourself..."
        className="h-10 w-full rounded-lg border border-white border-opacity-20 bg-transparent pl-2 text-white placeholder-white placeholder-opacity-20"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div key={post.id} className="border-b border-zinc-500 p-4">
      <div className="flex h-full items-center gap-2">
        <Image
          src={author.imageUrl}
          alt="Profile image"
          className="m-2 flex aspect-square h-10 rounded-lg"
          width={40}
          height={40}
        />
        <div className="gap-2">
          <div className="flex gap-1 font-bold text-white">
            @{author.username}
            <div className="font-normal opacity-50">
              • {dayjs(post.createdAt).fromNow()}
            </div>
          </div>
          {post.content}
        </div>
      </div>
    </div>
  );
};

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>Something went wrong</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-zinc-500 md:max-w-2xl">
          <div className="flex border-b border-zinc-500 bg-zinc-950 px-4 py-2">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && (
              <div className="flex h-full w-full justify-between gap-4">
                <CreatePostWizard />
                <SignOutButton />
              </div>
            )}
          </div>
          <div className="flex flex-col">
            {[...data, ...data]?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        </div>
      </main>
    </>
  );
}
